name: Feature Request
description: Suggest a new feature or enhancement for the Levitador Benchmark
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your proposal.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: A clear and concise description of the feature you'd like to see
      placeholder: Brief summary of the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve. Is your feature request related to a problem?
      placeholder: I'm frustrated when... / It would be useful to have... / Currently there's no way to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: Describe your proposed solution in detail...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternatives you've considered...

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - New optimization algorithm integration
        - Data handling and processing
        - Visualization and plotting
        - Documentation improvement
        - Performance optimization
        - API enhancement
        - Testing and validation
        - New benchmark problem variant
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be useful
        - High - Important for my work
        - Critical - Blocking my use case
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case and how this feature would benefit the project
      placeholder: |
        I am working on... and this feature would help by...
        This would benefit the project/community by...
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: If applicable, provide a code example of how you envision using this feature
      placeholder: |
        ```python
        from levitador_benchmark import LevitadorBenchmark
        
        # Example of how the feature might be used
        problema = LevitadorBenchmark()
        problema.new_feature(...)
        ```
      render: python

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant papers, libraries, or implementations that might be helpful
      placeholder: |
        - Link to paper: https://...
        - Similar implementation: https://...
        - Related issue: #...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to contribute to implementing this feature?
      options:
        - label: I would be willing to implement this feature and submit a Pull Request
          required: false
        - label: I can help with testing and validation
          required: false
        - label: I can help with documentation
          required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues and pull requests to ensure this feature hasn't been requested before
          required: true
        - label: This feature aligns with the project's goals (optimization benchmark for metaheuristics)
          required: true
